/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAuthenticatedRouteRouteImport } from './routes/_app/_authenticated/route'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as AppAuthenticatedProfileRouteImport } from './routes/_app/_authenticated/profile'
import { Route as AppAuthenticatedRoutesCreateRouteImport } from './routes/_app/_authenticated/routes/create'
import { Route as AppRoutesRouteIdIndexRouteImport } from './routes/_app/routes/$routeId/index'
import { Route as AppAuthenticatedRoutesRouteIdEditIndexRouteImport } from './routes/_app/_authenticated/routes/$routeId/edit/index'
import { Route as AppAuthenticatedRoutesRouteIdEditStopsRouteImport } from './routes/_app/_authenticated/routes/$routeId/edit/stops'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AppAuthenticatedProfileRoute = AppAuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedRoutesCreateRoute =
  AppAuthenticatedRoutesCreateRouteImport.update({
    id: '/routes/create',
    path: '/routes/create',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppRoutesRouteIdIndexRoute = AppRoutesRouteIdIndexRouteImport.update({
  id: '/routes/$routeId/',
  path: '/routes/$routeId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedRoutesRouteIdEditIndexRoute =
  AppAuthenticatedRoutesRouteIdEditIndexRouteImport.update({
    id: '/routes/$routeId/edit/',
    path: '/routes/$routeId/edit/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRoutesRouteIdEditStopsRoute =
  AppAuthenticatedRoutesRouteIdEditStopsRouteImport.update({
    id: '/routes/$routeId/edit/stops',
    path: '/routes/$routeId/edit/stops',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/profile': typeof AppAuthenticatedProfileRoute
  '/routes/create': typeof AppAuthenticatedRoutesCreateRoute
  '/routes/$routeId/': typeof AppRoutesRouteIdIndexRoute
  '/routes/$routeId/edit/stops': typeof AppAuthenticatedRoutesRouteIdEditStopsRoute
  '/routes/$routeId/edit/': typeof AppAuthenticatedRoutesRouteIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/profile': typeof AppAuthenticatedProfileRoute
  '/routes/create': typeof AppAuthenticatedRoutesCreateRoute
  '/routes/$routeId': typeof AppRoutesRouteIdIndexRoute
  '/routes/$routeId/edit/stops': typeof AppAuthenticatedRoutesRouteIdEditStopsRoute
  '/routes/$routeId/edit': typeof AppAuthenticatedRoutesRouteIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_authenticated/profile': typeof AppAuthenticatedProfileRoute
  '/_app/_authenticated/routes/create': typeof AppAuthenticatedRoutesCreateRoute
  '/_app/routes/$routeId/': typeof AppRoutesRouteIdIndexRoute
  '/_app/_authenticated/routes/$routeId/edit/stops': typeof AppAuthenticatedRoutesRouteIdEditStopsRoute
  '/_app/_authenticated/routes/$routeId/edit/': typeof AppAuthenticatedRoutesRouteIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/profile'
    | '/routes/create'
    | '/routes/$routeId/'
    | '/routes/$routeId/edit/stops'
    | '/routes/$routeId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/profile'
    | '/routes/create'
    | '/routes/$routeId'
    | '/routes/$routeId/edit/stops'
    | '/routes/$routeId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_guest'
    | '/_app/_authenticated'
    | '/_guest/login'
    | '/_guest/register'
    | '/_app/'
    | '/_app/_authenticated/profile'
    | '/_app/_authenticated/routes/create'
    | '/_app/routes/$routeId/'
    | '/_app/_authenticated/routes/$routeId/edit/stops'
    | '/_app/_authenticated/routes/$routeId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authenticated': {
      id: '/_app/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_app/_authenticated/profile': {
      id: '/_app/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppAuthenticatedProfileRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/_authenticated/routes/create': {
      id: '/_app/_authenticated/routes/create'
      path: '/routes/create'
      fullPath: '/routes/create'
      preLoaderRoute: typeof AppAuthenticatedRoutesCreateRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/routes/$routeId/': {
      id: '/_app/routes/$routeId/'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId/'
      preLoaderRoute: typeof AppRoutesRouteIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authenticated/routes/$routeId/edit/': {
      id: '/_app/_authenticated/routes/$routeId/edit/'
      path: '/routes/$routeId/edit'
      fullPath: '/routes/$routeId/edit/'
      preLoaderRoute: typeof AppAuthenticatedRoutesRouteIdEditIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/_authenticated/routes/$routeId/edit/stops': {
      id: '/_app/_authenticated/routes/$routeId/edit/stops'
      path: '/routes/$routeId/edit/stops'
      fullPath: '/routes/$routeId/edit/stops'
      preLoaderRoute: typeof AppAuthenticatedRoutesRouteIdEditStopsRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
  }
}

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedProfileRoute: typeof AppAuthenticatedProfileRoute
  AppAuthenticatedRoutesCreateRoute: typeof AppAuthenticatedRoutesCreateRoute
  AppAuthenticatedRoutesRouteIdEditStopsRoute: typeof AppAuthenticatedRoutesRouteIdEditStopsRoute
  AppAuthenticatedRoutesRouteIdEditIndexRoute: typeof AppAuthenticatedRoutesRouteIdEditIndexRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedProfileRoute: AppAuthenticatedProfileRoute,
  AppAuthenticatedRoutesCreateRoute: AppAuthenticatedRoutesCreateRoute,
  AppAuthenticatedRoutesRouteIdEditStopsRoute:
    AppAuthenticatedRoutesRouteIdEditStopsRoute,
  AppAuthenticatedRoutesRouteIdEditIndexRoute:
    AppAuthenticatedRoutesRouteIdEditIndexRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppRoutesRouteIdIndexRoute: typeof AppRoutesRouteIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppRoutesRouteIdIndexRoute: AppRoutesRouteIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
